server:
  port: 8080

#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: testLatticeApp

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

spring.social.twitter.appId: ogIANEpF2RkLxvHrzO0Cu5sVi
spring.social.twitter.appSecret: UbOselGMS6lmGQrey3NsjxO231UzWfOG8akh7Nhc6wbbxtBMQE

logging:
  level:
    ROOT: INFO



spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: false
spring.mail.properties.mail.smtp.starttls.required: false

spring.mail.host: 10.150.1.19
spring.mail.port: 25
spring.mail.username: notifier@socialfocus.com.ar
spring.mail.password:

emailCustom.emailSender: "notifier@socialfocus.com.ar"
emailCustom.emailSenderDescription: "Equipo de cuentas SocialFocus"
emailCustom.notificationTitle: "Confirmación de seguridad de la cuenta SocialFocus"

token.expiration: 1


  